name = "RememberingHome"
love_version = "11.3"

build_directory = "../release"
love_files = [
	"*/*",
]

[windows]
[windows.exe_metadata]
CompanyName = "flamendless"
LegalCopyright = "Copyright of flamendless studio 2020-2030"

[linux]
[linux.desktop_file_metadata]
Comment="Remembering Home - a game by flamendless studio"
Categories="Game;"
